apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: ace-server-deploy
spec:
  params:
    - name: project
      description: Specify the name of the project being built.
      default: inventory_asuh
      type: string
    - name: buildversion
      description: Docker image version for the BAR file
      default: ""
      type: string
    - name: env
      default: "dev"
      description: Specfiy the current environment. It is used in computing the Helm release name.
      type: string
    - name: production
      default: "false"
      description: Specifies if the deployment is production-like with High Availability enabled. Default [false]
      type: string
    - name: namespace
      default: "ace"
      description: Specify the namespace you want the pipeline to run in.
      type: string
    - name: pipeline-name
      description: Name of the pipeline for the health check
      default: "ace-server-deploy-apic"
  resources:
    - name: source
      type: git
    - name: image
      type: image
  tasks:
  - name: generate-bar
    resources:
      inputs:
      - name: source
        resource: source
    params:
      - name: project
        value: $(params.project)
    taskRef:
      name: generate-bar
  - name: build-image
    resources:
      inputs:
      - name: source
        resource: source
      outputs:
      - name: image
        resource: image
    params:
      - name: buildversion
        value: $(params.buildversion)
      - name: dockerfileLocation
        value: ./workspace/$(params.project)/Dockerfile
    taskRef:
      name: build-bar
    runAfter:
    - generate-bar
  - name: install-ace-server
    taskRef:
      name: install-ace-server
    params:
    - name: production
      value: $(params.production)
    - name: env
      value: $(params.env)
    - name: integrationComponent
      value: ace-server
    - name: project
      value: $(params.project)
    - name: buildversion
      value: $(params.buildversion)
    - name: namespace
      value: $(params.namespace)
    resources:
      inputs:
      - name: source
        resource: source
      - name: image
        resource: image
    runAfter:
    - build-image
  - name: health-check
    taskRef:
      name: smoke-tests
    params:
      - name: project
        value: $(params.project)
      - name: namespace
        value: $(params.namespace)
      - name: pipeline-name
        value: $(params.pipeline-name)
    runAfter:
      - install-ace-server
